# Generated by Django 3.2.3 on 2021-05-29 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figurines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('lenght', models.PositiveIntegerField(default=0, verbose_name='Длина')),
                ('width', models.PositiveIntegerField(default=0, verbose_name='Ширина')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('Anime', models.CharField(max_length=255, verbose_name='Тайтл')),
                ('production', models.CharField(max_length=255, verbose_name='Производство')),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dakimakura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('lenght', models.CharField(max_length=255, verbose_name='Длина')),
                ('width', models.CharField(max_length=255, verbose_name='Ширина')),
                ('material', models.CharField(max_length=255, verbose_name='Материал')),
                ('anime', models.CharField(max_length=255, verbose_name='Тайтл')),
                ('person', models.CharField(max_length=255, verbose_name='Персонаж')),
                ('print_method', models.CharField(max_length=255, verbose_name='Метод печати')),
                ('production', models.CharField(max_length=255, verbose_name='Производство')),
                ('complect_pillow', models.BooleanField(default=True)),
                ('brand', models.CharField(max_length=255, verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
