# Generated by Django 3.2.3 on 2021-06-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20210612_1548'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dakimakura',
            new_name='Dakimakuras',
        ),
    ]
